<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Category Product</name>
   <tag></tag>
   <elementGuidId>c7663ef0-27a9-40f5-81fe-08325fa98ffb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='header_search_category']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#header_search_category</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dbcc163e-158e-4a84-af8d-10da55f4b0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>search_category</value>
      <webElementGuid>236f9d78-2fc9-47a5-beb7-c62f7588a24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>header_search_category</value>
      <webElementGuid>9751fbd4-84e4-448f-878d-3a8fc61db05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header_search_select</value>
      <webElementGuid>789505fe-563a-416b-87f7-1f263865e2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
										Select CategoryUncategorizedCocoqua ココナッツDu-reamyドリアンHOME PAGEKOTAKOKI SETPIPILTIN COCOAREADY TO EATSEAFOODSPICESSTARTER SETスパイスブレンドテンペ新しいレシピセット</value>
      <webElementGuid>72842f7b-6bda-4383-9f81-a7c88c0f2f9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header_search_category&quot;)</value>
      <webElementGuid>606321ec-cbe6-43c7-bf05-4a98cc7f0c32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='header_search_category']</value>
      <webElementGuid>f6d85ae6-4e8b-4963-9b56-96039aee77ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Featured products'])[1]/preceding::select[1]</value>
      <webElementGuid>da9d9136-741c-405f-9d22-181a6795be90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cap'])[1]/preceding::select[1]</value>
      <webElementGuid>150dac41-c6f8-469a-80d4-e1b80c50d869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>54e242c4-9a91-48bf-a4d0-774a4119096f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'search_category' and @id = 'header_search_category' and (text() = '
										Select CategoryUncategorizedCocoqua ココナッツDu-reamyドリアンHOME PAGEKOTAKOKI SETPIPILTIN COCOAREADY TO EATSEAFOODSPICESSTARTER SETスパイスブレンドテンペ新しいレシピセット' or . = '
										Select CategoryUncategorizedCocoqua ココナッツDu-reamyドリアンHOME PAGEKOTAKOKI SETPIPILTIN COCOAREADY TO EATSEAFOODSPICESSTARTER SETスパイスブレンドテンペ新しいレシピセット')]</value>
      <webElementGuid>faff5101-2b02-413c-b85b-ba1e77ced327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
