<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit Newsletter</name>
   <tag></tag>
   <elementGuidId>be330075-3e1f-432d-86d9-12e4b6195128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='wpforms-submit-291']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wpforms-submit-291</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9a4baca6-1a0f-410f-ac99-97704f0d77a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>95838d13-bff9-4ed0-9796-523b53957db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wpforms[submit]</value>
      <webElementGuid>5d1c91c3-eb94-46be-a212-a458ee68d260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wpforms-submit-291</value>
      <webElementGuid>f6413578-a957-4478-a087-0bb24ddd6fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wpforms-submit</value>
      <webElementGuid>7f205ce9-5a5a-40b4-b289-3b96e0c22683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-alt-text</name>
      <type>Main</type>
      <value>Sending...</value>
      <webElementGuid>ed190918-56fc-4bef-aa1a-62b8c2944a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-submit-text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>28f95063-5a9a-4018-93a1-c4d2d4b5cfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>assertive</value>
      <webElementGuid>37c7f541-812e-42c2-8669-ae3b3f728d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>wpforms-submit</value>
      <webElementGuid>86acd398-53f2-4cb2-acdb-2e5405e7c852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>c417e6f7-0c8e-471b-9037-5a5b0938040e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wpforms-submit-291&quot;)</value>
      <webElementGuid>901aa498-5067-4a41-a0a4-67cfdb6dfd99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='wpforms-submit-291']</value>
      <webElementGuid>2aacd983-ffe4-4a25-993d-19f289ae27a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='wpforms-form-291']/div[2]/button</value>
      <webElementGuid>f9409cc9-0678-4487-941a-912538910475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::button[1]</value>
      <webElementGuid>cb31334e-fee6-441b-9448-94c8dcd480a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='地図&amp;アクセス方法'])[1]/preceding::button[1]</value>
      <webElementGuid>d5a827a6-4a1c-41e7-92d6-2668f8b767db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='お問い合わせ'])[1]/preceding::button[1]</value>
      <webElementGuid>fb0ba7f2-bf4e-4ad5-a5c9-adf1f57b6453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>a14fe4f2-487e-403a-adde-278aa8e4c1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>7c58ef5f-9b89-40bb-ad24-964c2baebecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'wpforms[submit]' and @id = 'wpforms-submit-291' and (text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>06c263c7-db23-4363-961d-e3cf4d5c5483</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
