<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input Address</name>
   <tag></tag>
   <elementGuidId>d90ea467-9a1a-4260-b614-1fb2d6c8d006</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Relative_adress-297']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Relative_adress-297</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6bb0aaa-d9f0-4817-a632-3d69905e1de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>60a0d5d8-67c3-4972-b15b-6a99bedf1f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>um-form-field um-error </value>
      <webElementGuid>952e6172-b20f-4401-9700-c245ee837ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2747f741-a9fc-4c76-a635-656857bda051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>fc97d358-4ef4-4a7d-b42b-1702513597fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Relative_adress-297</value>
      <webElementGuid>80d4130d-25be-4fb7-8a5f-b2cdd1da7d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>Relative_adress</value>
      <webElementGuid>c05d725e-5141-4e56-8976-e06f55bebcbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Relative_adress-297&quot;)</value>
      <webElementGuid>85a58fa7-ebdb-4782-a457-1efd005cae05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Relative_adress-297']</value>
      <webElementGuid>8932b39f-13b8-4bcc-b0a9-8e51d23c4003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='um_field_297_Relative_adress']/div[2]/input</value>
      <webElementGuid>b1119a03-6d7e-411a-818c-45d1dd665d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>4ad2d482-efac-4dc6-bdf3-911919a8c6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'Relative_adress-297' and @id = 'Relative_adress-297']</value>
      <webElementGuid>f097615d-911f-4725-93ca-5e44a99f4368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
